- name: Launch a VM
  environment: "{{ proxy_env }}"
  openstack.cloud.server:
          image: "{{ 'Baremetal - Ubuntu 20.04' if flavor.startswith('bm') else 'NVIDIA GPU Cloud (NGC)' if 'G' in tags else 'Ubuntu 20.04' }}"
          name: "{{ nodename }}"
          key_name: "{{ keyname }}"
          availability_zone: nova
          flavor: "{{ flavor }}"
          state: present
          network: "{{ 'Ext-Net-Baremetal' if flavor.startswith('bm') else 'Ext-Net' }}"
          region_name: "{{ region }}"
          meta: "{{ 'soft_raid=0' if flavor.startswith('bm') else 'x=0' }}"
  register: vm
- name: Add VM to inventory
  add_host:
          name: "{{ nodename }}"
          ansible_host: "{{ vm.server.public_v4 }}"
          groups: ovh
- name: Complete host related variables
  ansible.builtin.script:
      cmd: > 
        "{{ inventory_dir }}"/scitq-inventory
        --for-host "{{ nodename }}"
        --variable ansible_host --value "{{ vm.server.public_v4 }}"
        --variable ipv4 --value "{{ vm.server.public_v4 }}" 
        --variable ipv6 --value "{{ vm.server.public_v6 }}"
        --change-etchosts