"""Modifying defaults and adding detail in workers

Revision ID: aff13e566140
Revises: 
Create Date: 2023-12-07 09:04:12.580597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff13e566140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.alter_column('concurrency',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('concurrency',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('provider')
        batch_op.drop_column('region')
        batch_op.drop_column('flavor')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
