"""Add progress in Job

Revision ID: c924c0681070
Revises: bc1934d5d8d4
Create Date: 2024-10-25 19:10:29.877558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c924c0681070'
down_revision = 'bc1934d5d8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progression', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('progression')

    # ### end Alembic commands ###
